# Generated by Django 4.1.2 on 2022-10-28 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_aboutmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="aboutModel",
        ),
    ]
