# Generated by Django 4.1.2 on 2022-11-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_fooditemsmodel_dressmodel_accesoriesmodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dressmodel",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="electronicsmodel",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="fooditemsmodel",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="grocerymodel",
            name="parent",
        ),
        migrations.AddField(
            model_name="productmodel",
            name="size",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="AccesoriesModel",
        ),
        migrations.DeleteModel(
            name="DressModel",
        ),
        migrations.DeleteModel(
            name="ElectronicsModel",
        ),
        migrations.DeleteModel(
            name="FooditemsModel",
        ),
        migrations.DeleteModel(
            name="GroceryModel",
        ),
    ]
