# Generated by Django 4.1.2 on 2022-11-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_productmodel_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartmodel",
            name="size",
            field=models.CharField(default=0, max_length=5),
        ),
    ]
