# Generated by Django 4.1.2 on 2022-11-12 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_addressmodel_locationmodel_profilemodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='dob',
        ),
    ]
